on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited chains.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate chain.json schema
        run: |
          json_files=($(find . -name 'chain.json' | grep -v '_template/'))
          all_names=()
          for json_file in "${json_files[@]}"; do
            # Validate schema
            if ! jsonschema -i "$json_file" ./chain.schema.json; then
              echo "Schema validation failed for $json_file"
              exit 1
            fi
            # Check for duplicate chain names
            chain_name=$(jq -r '.chain_name' "$json_file")
            if [[ " ${all_names[@]} " =~ " ${chain_name} " ]]; then
              echo "Duplicate chain_name found: ${chain_name} in file ${json_file}"
              exit 1
            fi
            all_names+=("$chain_name")
          done
          echo "No duplicates found. All chain.json files are valid."